### ISSUE TITLE
Missing Graphics

### ISSUE THREAD

**Issue by WasserWelt** [exscape/6.002x#1]
I guess there might be some missing graphics in this repo, as I meet the error message "File not found" when I compile it.
They are:

> %1593
> \includegraphics[scale=1.5]{Graphics/opamp_transfer_function}
> 
> %2412
> \includegraphics[scale=1.5]{Graphics/comparator}
> 
> %2423
> \includegraphics[scale=1.5]{Graphics/comparator_noise}
> 
> %2480
> \includegraphics[scale=1.5]{Graphics/schmitt_noise}

Sorry to disturb you in 2023, more than a decade after you share your notes. I'd appreciate it if you could find the missing graphics. And it's OK that you can't. Thank you so much.

**Comment by exscape** [comment]
Haha, I didn't expect this! No worries though! I have the files and just added them to the master branch 😄 

It turns out I had \*.pdf in .gitignore (to not commit the generated PDF), and the graphics are PDF files, so I didn't notice they were missing from the git tree.
